### ISSUE TITLE
Since this mod is in 1.16 it is impossible to play it has conflicts now this update does not crash the game the block does not work no villager takes the profession is a useless block can you fix it?

### ISSUE THREAD

**Issue by FORJATARTARO** [Naetheline/KingVillager#7]

**Comment by drakray** [comment]
I am using Forge 1.16.4 - 35.1.11, kingvillager-1.6.1.jar, plus many other mods, and it is working
what versions are you using?, Both Minecraft, Forge, and the mod's?

**Comment by drakray** [comment]
I am using Forge 1.16.4 - 35.1.11, kingvillager-1.6.1.jar, plus many other mods, and it is working
what versions are you using?, Both Minecraft, Forge, and the mod's?

(I use the alternate .json for the throne model, from the pull request)

![2020-12-10_20 45 18](https://user-images.githubusercontent.com/4303126/101851788-3c398580-3b2a-11eb-8bb6-362d437df4f9.png)
